name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Get current date
        id: date
        run: echo "date=$(TZ=Asia/Tokyo date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v5.0.0

      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Update dependencies
        run: |
          bundle config set frozen false
          bundle update
          bundle exec rbs collection update

      - name: Validate RBS
        run: |
          bundle exec rbs --log-level=info -I sig validate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: 'chore: update dependencies'
          title: "Update dependencies ${{ steps.date.outputs.date }}"
          body: |
            This PR updates the following dependencies:
            - Updated gems via `bundle update`
            - Updated RBS collection via `rbs collection update`
          branch: update-dependencies-${{ steps.date.outputs.date }}
          delete-branch: true
          base: main
          draft: always-true
